apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - cluster-issuer.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.20.3
    releaseName: cert-manager
    namespace: cert-manager
    valuesInline:
      installCRDs: true

  - name: cert-manager-desec-webhook
    repo: oci://ghcr.io/pr0ton11/helm
    version: 0.1.2 
    releaseName: cert-manager-desec-webhook
    namespace: cert-manager

patches:
  # Use a patch to force the deSEC Webhook to wave 1. 
  - target:
      kind: Deployment
      name: cert-manager-desec-webhook
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: cert-manager-desec-webhook
        annotations:
          argocd.argoproj.io/sync-wave: "1"

