apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-podinfo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/NishitRai/k8s-gitops-infra.git' 
    targetRevision: HEAD
    path: apps/podinfo/overlays/staging/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: podinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
