apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ip-pool-patch.yaml

# Argo CD to bypass the strict sync requirements for any broken upstream CRD metadata
commonAnnotations:
  argocd.argoproj.io/compare-options: IgnoreExtraneous
